# ============================================================
# NEXUS ? application.properties
# Base de datos: Supabase (PostgreSQL)
# ============================================================

# --- Datasource ---
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.hcmnmispoittwqwyahos
spring.datasource.password=porta3152305737
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- JWT ---
jwt.secret=nexus-secret-key-super-segura-2024-universidad-proyecto
jwt.expiration=86400000

# --- Server ---
server.port=8080

# --- CORS (React Vite) ---
spring.web.cors.allowed-origins=http://localhost:5173,http://localhost:5174